namespace nkast.Wasm.Canvas.WebGL
{
    public enum WebGL2PNameInteger
    {
        MAX_TEXTURE_IMAGE_UNITS          = 0x8872,
        MAX_VERTEX_TEXTURE_IMAGE_UNITS   = 0x8B4C,
        MAX_COMBINED_TEXTURE_IMAGE_UNITS = 0x8B4D,
        MAX_VERTEX_ATTRIBS           = 0x8869,
        MAX_TEXTURE_SIZE             = 0x0D33,
        MAX_CUBE_MAP_TEXTURE_SIZE    = 0x851C,
        MAX_FRAGMENT_UNIFORM_VECTORS = 0x8DFD,
        MAX_RENDERBUFFER_SIZE        = 0x84E8,
        MAX_VARYING_VECTORS          = 0x8DFC,
        MAX_VERTEX_UNIFORM_VECTORS   = 0x8DFB,
        
        // WebGL2
        MAX_3D_TEXTURE_SIZE = 0x8073,
        MAX_ARRAY_TEXTURE_LAYERS = 0x88FF,
        MAX_COLOR_ATTACHMENTS = 0x8CDF,
        MAX_COMBINED_UNIFORM_BLOCKS = 0x8A2E,
        MAX_DRAW_BUFFERS = 0x8824,
        MAX_ELEMENTS_INDICES = 0x80E9,
        MAX_ELEMENTS_VERTICES = 0x80E8,
        MAX_FRAGMENT_INPUT_COMPONENTS = 0x9125,
        MAX_FRAGMENT_UNIFORM_BLOCKS = 0x8A2D,
        MAX_FRAGMENT_UNIFORM_COMPONENTS = 0x8B49,
        MAX_SAMPLES = 0x8D57,
        MAX_UNIFORM_BUFFER_BINDINGS = 0x8A2F,
        MAX_VARYING_COMPONENTS = 0x8B4B,
        MAX_VERTEX_OUTPUT_COMPONENTS = 0x9122,
        MAX_VERTEX_UNIFORM_BLOCKS = 0x8A2B,
        MAX_VERTEX_UNIFORM_COMPONENTS = 0x8B4A,
    }
}
